* 🦬 emacs.tv

[[https://emacs.tv][emacs.tv]] aggregates videos related to our favorite text editor [[https://www.gnu.org/software/emacs/][GNU Emacs]].

This project was born out of a [[https://social.sachachua.com/@sacha/statuses/01JF94JQQNNRXMTKN3Y1774TFP][collaboration]] between [[https://sachachua.com/blog/][Sacha Chua]] and [[https://lmno.lol/alvaro][Alvaro Ramirez]].

* Watch videos

You can use the random feature at https://emacs.tv (requires Javascript), search for text in the page, or filter by tag/speaker.

If you have the [[https://mpv.io][MPV media player]] and the [[https://github.com/kljohann/mpv.el/tree/master][mpv.el]] package (available on MELPA and NonGNU ELPA), you can install emacstv.el from this repo:

#+begin_src emacs-lisp
(use-package emacstv
	:vc (:url "https://github.com/emacstv/emacstv.github.io"))
#+end_src

Then use:

- ~M-x emacstv-background-mode~: play one video after another until you disable it by calling ~M-x emacstv-background-mode~ again. You can use ~>~ to go to the next video in the shuffled playlist or ~<~ in the MPV window to go to the previous one, or use the commands ~mpv-playlist-next~ and ~mpv-playlist-prev~ in Emacs.
- ~M-x emacstv-play~: select a video by typing in part of its title or speakers
- ~M-x emacstv-play-random~: play a random video
- ~M-x emacstv-jump-to-current-video~: jump to the entry for the current video.
- ~M-x mpv-pause~: pause or play the video
- ~M-x mpv-volume-decrease~ and ~mpv-volume-increase~ to manage the volume.

You can search for videos with ~M-x emacstv-agenda-search~. If you have [[https://github.com/alphapapa/org-ql][org-ql]], you can use ~M-x emacstv-org-ql-search~.
You can play the video at the current line with ~M-x emacstv-play-at-point~.

To watch YouTube videos with subtitles, you may want to add something like this to your mpv.conf (~~/.config/mpv/mpv.conf~ on my system):

#+begin_example
ytdl-raw-options='ignore-config=,sub-langs="en,en-US",write-subs=,write-auto-subs='
sub-auto=fuzzy
slang=en,eng,enUS,en-US
#+end_example

If you don't want the video window to be resized for each window, you can try something like this in your ~mpv.conf~:

#+begin_example
force-window
force-window-position
no-keepaspect-window
geometry=50%x50%-0-0
#+end_example

* Add videos

Help keep =emacs.tv= fresh and interesting by submitting new videos.

You can e-mail [[mailto:sacha@sachachua.com][sacha@sachachua.com]] with a link to the video, or you can add videos by following these steps:

- [[https://github.com/emacstv/emacstv.github.io/fork][Fork]] this repository.
- Add a new entry to [[https://raw.githubusercontent.com/emacstv/emacstv.github.io/refs/heads/main/videos.org][videos.org]]. Be sure to add as many of the fields provided as possible and _please include tags_. You can either follow the example below or use =M-x emacstv-add-from-youtube= helper from [[https://github.com/emacstv/emacstv.github.io/blob/main/emacstv.el][emacstv.el]].

For example:

#+begin_src org
  ,* EmacsConf.org: How we use Org Mode and TRAMP to organize and run a multi-track conference :emacsconf:emacsconf2023:org:tramp:
  :PROPERTIES:
  :DATE: 2023-12-03
  :URL: https://emacsconf.org/2023/talks/emacsconf
  :MEDIA_URL: https://media.emacsconf.org/2023/emacsconf-2023-emacsconf--emacsconforg-how-we-use-org-mode-and-tramp-to-organize-and-run-a-multitrack-conference--sacha-chua--main.webm
  :YOUTUBE_URL: https://www.youtube.com/watch?v=uTregv3rNl0
  :TOOBNIX_URL: https://toobnix.org/w/eX2dXG3xMtUHuuBz4fssGT
  :TRANSCRIPT_URL: https://media.emacsconf.org/2023/emacsconf-2023-emacsconf--emacsconforg-how-we-use-org-mode-and-tramp-to-organize-and-run-a-multitrack-conference--sacha-chua--main.vtt
  :SPEAKERS: Sacha Chua
  :SERIES: EmacsConf 2023
  :END:
#+end_src

- Submit a pull request.

* Improve tags/metadata

Many videos could really do with more tags and additional metadata. Please help us by submitting pull requests with metadata improvements.

You can search for videos with ~M-x emacstv-agenda-search~.

If you have [[https://github.com/alphapapa/org-ql][org-ql]], you can use ~M-x
emacstv-org-ql-search~. For example, you can
search for ~(and (heading "python") (not (tags
"python")))~ to find videos that have "python" in
the heading but not the tags.

Mark items with ~m~, unmark them with ~u~, and add or remove tags from marked items with ~B +~ and ~B -~.
You can play the video at the current line with ~M-x emacstv-play-at-point~.
