* 🦬 emacs.tv

[[https://emacs.tv][emacs.tv]] aggregates videos related to our favorite text editor [[https://www.gnu.org/software/emacs/][GNU Emacs]].

This project was born out of a [[https://social.sachachua.com/@sacha/statuses/01JF94JQQNNRXMTKN3Y1774TFP][collaboration]] between [[https://sachachua.com/blog/][Sacha Chua]] and [[https://lmno.lol/alvaro][Alvaro Ramirez]].

* Watch videos

You can use the random feature at https://emacs.tv (requires Javascript), search for text in the page, or filter by tag/speaker.

If you have the [[https://mpv.io][MPV media player]] and the [[https://github.com/kljohann/mpv.el/tree/master][mpv.el]] package (available on MELPA and NonGNU ELPA), you can install emacstv.el from this repo:

#+begin_src emacs-lisp
(use-package emacstv
	:vc (:url "https://github.com/emacstv/emacstv.github.io"))
#+end_src

Then use:

- ~M-x emacstv-play-random~: play a random video
- ~M-x emacstv-background-mode~: play one video after another until you disable it by calling ~M-x emacstv-background-mode~ again.
- ~M-x emacstv-play~: select a video by typing in part of its title or speakers

* Add videos

Help keep =emacs.tv= fresh and interesting by submitting new videos.

You can e-mail [[mailto:sacha@sachachua.com][sacha@sachachua.com]] with a link to the video, or you can add videos by following these steps:

- [[https://github.com/emacstv/emacstv.github.io/fork][Fork]] this repository.
- Add a new entry to [[https://raw.githubusercontent.com/emacstv/emacstv.github.io/refs/heads/main/videos.org][videos.org]]. Be sure to add as many of the fields provided as possible and _please include tags_. You can either follow the example below or use =M-x emacstv-add-from-youtube= helper from [[https://github.com/emacstv/emacstv.github.io/blob/main/emacstv.el][emacstv.el]].

For example:

#+begin_src org
  ,* EmacsConf.org: How we use Org Mode and TRAMP to organize and run a multi-track conference :emacsconf:emacsconf2023:org:tramp:
  :PROPERTIES:
  :DATE: 2023-12-03
  :URL: https://emacsconf.org/2023/talks/emacsconf
  :MEDIA_URL: https://media.emacsconf.org/2023/emacsconf-2023-emacsconf--emacsconforg-how-we-use-org-mode-and-tramp-to-organize-and-run-a-multitrack-conference--sacha-chua--main.webm
  :YOUTUBE_URL: https://www.youtube.com/watch?v=uTregv3rNl0
  :TOOBNIX_URL: https://toobnix.org/w/eX2dXG3xMtUHuuBz4fssGT
  :TRANSCRIPT_URL: https://media.emacsconf.org/2023/emacsconf-2023-emacsconf--emacsconforg-how-we-use-org-mode-and-tramp-to-organize-and-run-a-multitrack-conference--sacha-chua--main.vtt
  :SPEAKERS: Sacha Chua
  :SERIES: EmacsConf 2023
  :END:
#+end_src

- Submit a pull request.

* Improve tags/metadata

Many videos could really do with more tags and additional metadata. Please help us by submitting pull requests with metadata improvements.
